name: deploy

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - 'docker-compose.yml'
      - 'docker-compose.ci.yml'
      - 'src/WebApiPlayground/appsettings.Development.json'
      - 'src/WebApiPlayground/appsettings.Testing.json'
    branches: [ 'main' ]

  workflow_dispatch:

env:
  DOCKER_ARTIFACT_REPOSITORY: ${{ secrets.ACR_LOGIN_SERVER_ADDRESS }}
  DOCKER_ARTIFACT_REPOSITORY_NAME: ${{ secrets.ACR_NAME }}

jobs:

  continuous-integration:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy:
    needs: [continuous-integration]
    runs-on: ubuntu-latest
    if: needs.continuous-integration.result == 'success'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - name: Generate next release number
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          default_bump: major
          dry_run: true
          
      - name: Login to Azure
        uses: Azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CLIENT_SP_CREDENTIALS }}
          
      - name: Docker login to ACR
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.DOCKER_ARTIFACT_REPOSITORY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      - name: Build new Docker image
        run: |
          docker build -t "${{ env.DOCKER_ARTIFACT_REPOSITORY }}/webapi:${{ steps.tag_version.outputs.new_tag }}" -f src/WebApiPlayground/Dockerfile .

      - name: Push new image to ACR
        run: |
          docker push "${{ env.DOCKER_ARTIFACT_REPOSITORY }}/webapi:${{ steps.tag_version.outputs.new_tag }}"
          
      - name: Deploy new image to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src/WebApiPlayground
          resourceGroup: rg-webApiPlayground
          containerAppEnvironment: cae-api
          containerAppName: capp-webapi-playground          
          acrName: ${{ env.DOCKER_ARTIFACT_REPOSITORY_NAME }}
          imageToDeploy: ${{ env.DOCKER_ARTIFACT_REPOSITORY }}/webapi:${{ steps.tag_version.outputs.new_tag }}
          environmentVariables: "ENV=Staging"

      - name: Create a new GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      