name: test

on:
  pull_request:
    branches: [ '**' ]
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'

      - name: Run 'dotnet restore'
        run: dotnet restore

      - name: Run 'dotnet build'
        id: dotnet-build
        run: |
          dotnet build 
          
      - name: Run 'dotnet test'
        id: dotnet-test
        run: dotnet test  